# Generated by Django 3.2.5 on 2022-07-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='image/')),
                ('user_name', models.CharField(max_length=30)),
                ('user_email', models.CharField(max_length=30)),
                ('user_date_of_birth', models.DateField()),
                ('user_phone_number', models.CharField(max_length=30)),
                ('introduce', models.FileField(upload_to='introduce/')),
            ],
        ),
    ]
