# Generated by Django 3.2.5 on 2022-08-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20220810_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='goods_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
