# Generated by Django 3.2.5 on 2022-08-24 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
