# Generated by Django 3.2.5 on 2022-08-24 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '顧客'), (1, '廠商')], default=False),
        ),
    ]
